### ISSUE TITLE
How to clear layers?

### ISSUE THREAD

**Issue by xlcrr** [robertleeplummerjr/Leaflet.glify#101]
When the user pans around the map, I would like to clear all point data and re-load it

Previously this was `markers.clearLayers()`

How can this be achieved with this awesome plugin?

Thanks <3

**Comment by samuset** [comment]
Hi, this works for me:

`glify.remove();`

`glify` being the variable set up as `L.glify.points( {...`

See docs about `remove()`: [https://github.com/robertleeplummerjr/Leaflet.glify](https://github.com/robertleeplummerjr/Leaflet.glify)

**Comment by xlcrr** [comment]
I am getting this error

```
leaflet_glify__WEBPACK_IMPORTED_MODULE_8___default.a.points.remove is not a function
```

using

```
glify.remove()
glify.points.remove()
```

compiled with Laravel-mix, webpack plugin for laravel + vue

**Comment by samuset** [comment]
Not sure what this might be. I downloaded and built the lib manually (npm version (3.1.0) is not the latest 3.2.0) and imported it manually. Maybe try that?

**Comment by robertleeplummerjr** [comment]
When you call:
* `glify.points()`
* `glify.lines()`
* `glify.shapes()`


You are creating variables, instances that you'll want to interact with.  To this end, try this:
* ```js
  const myPoints = glify.points({ map, data });
  myPoints.remove();
  ```
* ```js
  const myLines = glify.lines({ map, data });
  myLines.remove();
  ```
* ```js
  const myShapes = glify.shapes({ map, data });
  myShapes.remove();
  ```

Conversely, you can add the layer back to a map:
* ```js
  const myPoints = glify.points();
  myPoints.addTo(map);
  ```
* ```js
  const myLines = glify.lines();
  myLines.addTo(map);
  ```
* ```js
  const myShapes = glify.shapes();
  myShapes.addTo(map);
  ```

**Comment by robertleeplummerjr** [comment]
[Here is an example](https://observablehq.com/d/a0461c28fe9bd892).

**Comment by xlcrr** [comment]
Thanks for the reply. I tried returning a `points` var and using this to clear the layers but no success. The link you shared does not work as a guest. You can see my implementation here if you are interested to see where I am going wrong https://github.com/OpenLitterMap/openlittermap-web/blob/master/resources/js/views/global/Supercluster.vue thanks for this amazing plugin- huge help!

**Comment by xlcrr** [comment]
I got this working at last by moving `points.remove()` before the request. I was trying to handle it in the response
