### ISSUE TITLE
How to remove or visible on/off of glify layers from map objects?

### ISSUE THREAD

**Issue by osper66** [robertleeplummerjr/Leaflet.glify#11]

**Comment by osper66** [comment]
”map.removeLayer" seems not to work for these layers.

 Thanks for advance.

**Comment by robertleeplummerjr** [comment]
As of https://github.com/robertleeplummerjr/Leaflet.glify/blob/548c994d30309b54f0edafe0f9cbe4acadff36b9/src/js/glify/points.js#L345 you just:

```js
const points = L.glify.points({...map});
points.remove();
points.addTo(map);
```

**Comment by osper66** [comment]
Thanks you.

 It works.

 However I think it will better in L.control.layers.

 Regards.

**Comment by trafficonese** [comment]
This will not remove the layer from `L.glify.instances` am I correct? Is there a way to fully remove a layer?

**Comment by charlieforward9** [comment]
> As of
> 
> https://github.com/robertleeplummerjr/Leaflet.glify/blob/548c994d30309b54f0edafe0f9cbe4acadff36b9/src/js/glify/points.js#L345
> 
> you just:
> ```js
> const points = L.glify.points({...map});
> points.remove();
> points.addTo(map);
> ```

How do we achieve this same functionality now?
