### ISSUE TITLE
How to display geojson points

### ISSUE THREAD

**Issue by osper66** [robertleeplummerjr/Leaflet.glify#12]
Hi.

 Current Leaflet.glify dosen’t support geojson point. I’d like to display properties on pop up event like geojson polygon.

**Comment by osper66** [comment]
Hi.

 I could only display geojson point in following modification, but I couldn't display property info.

  wget(['tokyo_busstops.geojson'], function(points) {
    //added
    gp=JSON.parse(points);
    points = gp;
 
    pnts=[]

    for(var i =0;i<gp.features.length;i++)
      pnts.push([gp.features[i].geometry.coordinates[1], gp.features[i].geometry.coordinates[0]]);
    points = pnts;
    // added done

    L.glify.points({
      map: map,
      click: function (e, point, xy) {
        //set up a standalone popup (use a popup as a layer)
        L.popup()
            .setLatLng(point)
            .setContent("GeoLocation :" + point[L.glify.longitudeKey] + ' , ' + point[L.glify.latitudeKey])
            .openOn(map);

        console.log(point);
      },
      //data: JSON.parse(points)
      data: points, //modified
      color: function(){return {r: 255, g: 0, b: 0}},
      size: 5
    });
    
  });

**Comment by osper66** [comment]
I could display geojson points' properties by pop up events in following code.

wget(['tokyo_busstops.geojson'], function(points) { //added gp=JSON.parse(points); points = gp;
pnts=[];
properties =[]

for(var i =0;i<gp.features.length;i++){
  pnts.push([gp.features[i].geometry.coordinates[1], gp.features[i].geometry.coordinates[0]]);
points = pnts;

//add point's coordinate info to properties
var properties0 = gp.features[i].properties;
properties0['x'] = gp.features[i].geometry.coordinates[0];
properties0['y'] = gp.features[i].geometry.coordinates[1];
properties.push(properties0);
};

//

L.glify.points({
  map: map,
  click: function (e, point, xy) {
    //set up a standalone popup (use a popup as a layer)

   //look for matched property
    var property = null;
    for(let p of this.properties)
        if(((p['x'] == point[L.glify.longitudeKey]) && (p['y'] == point[L.glify.latitudeKey]))){
     console.log(p);
     property = p;
      break;
};

    L.popup()
        .setLatLng(point)
        .setContent("GeoLocation :" + point[L.glify.longitudeKey] + ' , ' + point[L.glify.latitudeKey] + ', busstop name: ' + property['P11_001'])
        .openOn(map);

    console.log(point);
  },
  //data: JSON.parse(points)
  data: points, //modified
  properties : properties, //modified
  color: function(){return {r: 255, g: 0, b: 0}},
  size: 5
});
});

**Comment by robertleeplummerjr** [comment]
Looks like this was resolved.  Let me know if it was not.

**Comment by davewilliamstx** [comment]
I'm currently trying to get this to work - looks like a decent solution - it would be really cool if .points had the same geojson capabilities as .shapes to make using properties cleaner.
