### ISSUE TITLE
Polygon Boundary Lines Drawing Problem

### ISSUE THREAD

**Issue by osper66** [robertleeplummerjr/Leaflet.glify#13]
Hi.

   I found drawing polygon having many points were sometimes,especially on zooming in, connecting lines with skipping between points.
   Is this webgl's polygon tessellation problem?

   Could you have any idea for resolving this problem?

  Thanks for advance.

**Comment by robertleeplummerjr** [comment]
Do you have an example?

**Comment by osper66** [comment]
Thank you for your response.

 Here is my sample. Polygon fill is ok, but boundary line not correct.

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                               
"features": [
{ "type": "Feature", "properties": { "A27_005": "13209", "A27_006": "a", "A27_007": "a1", "A27_008": "a2" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 139.48487310685579, 35.519866250038667 ], [ 139.4848421069222, 35.51987724996156 ], [ 139.48473310715801, 35.519916249689778 ], [ 139.48460710736333, 35.519951249395774 ], [ 139.484544107396, 35.519958249269777 ], [ 139.48443910676602, 35.519867249265111 ], [ 139.48420810554799, 35.519692249204446 ], [ 139.48407710486555, 35.519594249167554 ], [ 139.48404410469155, 35.519569249158884 ], [ 139.48398110436423, 35.519522249140891 ], [ 139.48395110420421, 35.51949924913356 ], [ 139.48380910345267, 35.519391249097112 ], [ 139.48371810310576, 35.519342249033336 ], [ 139.4835701028862, 35.519314248826227 ], [ 139.48341610252535, 35.519265248650441 ], [ 139.48333810206802, 35.51919924864378 ], [ 139.48328310174912, 35.519153248638005 ], [ 139.48327210156668, 35.519126248672443 ], [ 139.4831981003102, 35.518940248912891 ], [ 139.48313509898958, 35.518744249192885 ], [ 139.48307209785554, 35.518576249416888 ], [ 139.48301909713044, 35.518469249536672 ], [ 139.48297509654731, 35.518383249630446 ], [ 139.48280609666978, 35.518407249282006 ], [ 139.48256209684891, 35.518442248778221 ], [ 139.48246609688755, 35.518451248589557 ], [ 139.48238809696355, 35.518465248422885 ], [ 139.48226109500865, 35.518176248775106 ], [ 139.48219009439956, 35.518087248826888 ], [ 139.48183209231999, 35.517787248790441 ], [ 139.48179109320421, 35.517921248449554 ], [ 139.48174909408158, 35.518054248108889 ], [ 139.48169109510198, 35.518209247695779 ], [ 139.48155409488487, 35.518181247508224 ], [ 139.4814940940449, 35.518057247649551 ], [ 139.48133609326311, 35.517945247592664 ], [ 139.48128609343198, 35.517972247449777 ], [ 139.48093009463958, 35.51816524643089 ], [ 139.48097809532356, 35.518266246314219 ], [ 139.48100709643668, 35.518432246033775 ], [ 139.48092809719245, 35.518548245661336 ], [ 139.48078409768712, 35.518627245247337 ], [ 139.48045809803466, 35.51869024454178 ], [ 139.48026409834489, 35.518743244090892 ], [ 139.48046710055002, 35.519067243803775 ], [ 139.48007510156955, 35.519233242774888 ], [ 139.47979910268822, 35.519410241930224 ], [ 139.47939210448445, 35.519693240640663 ], [ 139.47910510616069, 35.519954239608445 ], [ 139.47904210690666, 35.520068239268447 ], [ 139.47893910773044, 35.520195238831334 ], [ 139.47899710854333, 35.520315238694444 ], [ 139.47893410883597, 35.520361238490445 ], [ 139.47896910979713, 35.520504238266668 ], [ 139.47898511129401, 35.520728237847109 ], [ 139.47884311181576, 35.520811237428667 ], [ 139.47881611300312, 35.520990237022666 ], [ 139.47883311535358, 35.521342236348886 ], [ 139.47880211680666, 35.521561235855778 ], [ 139.47872711789, 35.521726235392443 ], [ 139.47870911879934, 35.52186323508645 ], [ 139.47857412000269, 35.522048234476443 ], [ 139.47839412172269, 35.52231223362844 ], [ 139.47848712464335, 35.522747232923777 ], [ 139.47850912548157, 35.522872232712885 ], [ 139.47848412698269, 35.523098232216441 ], [ 139.47845112782201, 35.523225231903773 ], [ 139.47828712867224, 35.523358231346222 ], [ 139.47827912906376, 35.523417231214005 ], [ 139.47828913237933, 35.523914230237779 ], [ 139.47825413475155, 35.524271229461554 ], [ 139.47781313465356, 35.524271228677556 ], [ 139.47759113481754, 35.524303228218891 ], [ 139.47732313517133, 35.524365227618446 ], [ 139.4770691356149, 35.524440227016889 ], [ 139.47682513627399, 35.524547226369108 ], [ 139.4765871371811, 35.524691225657996 ], [ 139.47621613887867, 35.524958224464442 ], [ 139.47594214000677, 35.525159223734335 ], [ 139.47673514322474, 35.525686224617111 ], [ 139.47698214426995, 35.525856224886219 ], [ 139.47719314521714, 35.526010225107335 ], [ 139.4773991460273, 35.526140225343553 ], [ 139.47767914725682, 35.526338225643336 ], [ 139.47818014952827, 35.526702226170002 ], [ 139.47820205515987, 35.526779913623827 ], [ 139.47823715119276, 35.526984225989331 ], [ 139.47826915178149, 35.527083225947223 ], [ 139.47831915272144, 35.527241225878107 ], [ 139.47846315430954, 35.527504225871112 ], [ 139.47855015490265, 35.527600225929774 ], [ 139.47859415520557, 35.527649225958996 ], [ 139.47860015548312, 35.527696225922668 ], [ 139.47834815885119, 35.528288224882672 ], [ 139.47826815971888, 35.528442224586442 ], [ 139.4782971603149, 35.528542224538 ], [ 139.47842716209973, 35.528838224473112 ], [ 139.47856016399544, 35.52915222439556 ], [ 139.478678165449, 35.529391224366329 ], [ 139.47868416583282, 35.529456224312 ], [ 139.47861416717171, 35.529690223953558 ], [ 139.47861416809161, 35.529847223796551 ], [ 139.47864016958687, 35.530100223589777 ], [ 139.47866917082055, 35.53030822343333 ], [ 139.47866617134662, 35.530398223337997 ], [ 139.47858117276763, 35.53064822293689 ], [ 139.47852317336958, 35.530756222725778 ], [ 139.4784471747744, 35.531003222343664 ], [ 139.47845017589933, 35.531195222156995 ], [ 139.47846317646824, 35.531291222084114 ], [ 139.47852917782825, 35.531517221975449 ], [ 139.47880617711149, 35.531368222616891 ], [ 139.47906517668045, 35.531270223175333 ], [ 139.47962917620788, 35.531137224311003 ], [ 139.47987817617877, 35.531109224781666 ], [ 139.48015117624522, 35.531095225281 ], [ 139.48052217739607, 35.531254225781552 ], [ 139.48064217791628, 35.531330225918886 ], [ 139.48071817848432, 35.531418225966 ], [ 139.48081017945663, 35.531572225975552 ], [ 139.48099117896169, 35.531472226397334 ], [ 139.48107417994331, 35.531628226388889 ], [ 139.48096018003326, 35.531654226160228 ], [ 139.48104918151603, 35.53189322607944 ], [ 139.48110218402797, 35.532307225759666 ], [ 139.48109918494291, 35.532460225601334 ], [ 139.48151218586051, 35.532570226225552 ], [ 139.48168818654892, 35.532666226442444 ], [ 139.48220518982194, 35.533153226874553 ], [ 139.48232919064242, 35.533275226973004 ], [ 139.48253719210157, 35.533504227136376 ], [ 139.48267119351121, 35.533737227171002 ], [ 139.48273819484788, 35.533965227090363 ], [ 139.48308319524222, 35.533994227672295 ], [ 139.48358619578724, 35.534031228524519 ], [ 139.48359819605022, 35.534076228505313 ], [ 139.48372519805022, 35.534414228424623 ], [ 139.48386719928391, 35.534615228491461 ], [ 139.48387719944355, 35.5346422284845 ], [ 139.48345819994054, 35.534779227632015 ], [ 139.48310920030855, 35.534885226931443 ], [ 139.48313320196789, 35.535175226716902 ], [ 139.48320820348556, 35.535434226617213 ], [ 139.48349020642189, 35.535919226669634 ], [ 139.48358920709421, 35.536026226742969 ], [ 139.48375220733888, 35.53605022699945 ], [ 139.48394020753221, 35.536062227309188 ], [ 139.48439620831223, 35.536146228009635 ], [ 139.4845102084449, 35.536156228194542 ], [ 139.48451920831491, 35.536132228231963 ], [ 139.48452420823889, 35.536118228253365 ], [ 139.48453120812457, 35.536097228284618 ], [ 139.48459820797089, 35.536062228431085 ], [ 139.48468820774755, 35.536012228630781 ], [ 139.48484020757121, 35.535963228935671 ], [ 139.48528120746289, 35.53589222975554 ], [ 139.48590720706989, 35.535749230962637 ], [ 139.48624820701389, 35.535699231595217 ], [ 139.48671320679691, 35.535606232483595 ], [ 139.4867312067579, 35.535597232523322 ], [ 139.48676320672823, 35.535588232587095 ], [ 139.48678920664355, 35.535570232649413 ], [ 139.48681620640656, 35.535525232739978 ], [ 139.48682120618321, 35.535485232787856 ], [ 139.48681620569823, 35.535400232862699 ], [ 139.48676720460588, 35.535213232961617 ], [ 139.48673520334353, 35.534994233120855 ], [ 139.48673320330255, 35.534987233124248 ], [ 139.48672520316123, 35.534963233133873 ], [ 139.48665020179089, 35.534730233231514 ], [ 139.48657420108287, 35.534614233212359 ], [ 139.48648520028689, 35.534484233183647 ], [ 139.48645020008789, 35.534453233152632 ], [ 139.48640419983056, 35.53441323311106 ], [ 139.48637119957621, 35.534372233093102 ], [ 139.48634619938389, 35.534341233079395 ], [ 139.48633819927088, 35.534322233083799 ], [ 139.48631419893189, 35.53426523309696 ], [ 139.48633519864555, 35.534212233185116 ], [ 139.48637719854324, 35.534189233281111 ], [ 139.48644819837523, 35.53415123344265 ], [ 139.48650919795122, 35.534069233629594 ], [ 139.48656019746389, 35.533977233808947 ], [ 139.48654019687254, 35.533875233873118 ], [ 139.48647019575489, 35.533686233933487 ], [ 139.48630419307315, 35.533242234072667 ], [ 139.48615618987574, 35.532747234304559 ], [ 139.48604818755504, 35.532387234472559 ], [ 139.48602918714303, 35.532323234502776 ], [ 139.48600918666176, 35.532248234542223 ], [ 139.48598418605883, 35.532154234591779 ], [ 139.48594218503968, 35.53199523467611 ], [ 139.48591018424582, 35.531871234743228 ], [ 139.48587718345181, 35.531747234808556 ], [ 139.48584818274173, 35.531636234867996 ], [ 139.48581718200586, 35.531521234927887 ], [ 139.4858021816415, 35.531464234958221 ], [ 139.48577418097028, 35.531359235013447 ], [ 139.48577318092603, 35.531352235018666 ], [ 139.48577918027408, 35.53124723513433 ], [ 139.48578617953515, 35.531128235265783 ], [ 139.48589817872195, 35.530988235604887 ], [ 139.48598217789217, 35.530848235894219 ], [ 139.48603817709011, 35.530715236126781 ], [ 139.48609956302738, 35.530532636512206 ], [ 139.48612317554492, 35.530461236531892 ], [ 139.48612917542906, 35.530442236561555 ], [ 139.48625617376447, 35.530166237063334 ], [ 139.48649017186528, 35.529845237800338 ], [ 139.48652217161057, 35.529802237900221 ], [ 139.48663417060791, 35.529634238267334 ], [ 139.48669016975359, 35.529494238506885 ], [ 139.48674616859009, 35.529305238795445 ], [ 139.48678116679929, 35.529018239144669 ], [ 139.48678816592098, 35.528878239297107 ], [ 139.48694616536471, 35.528779239677 ], [ 139.48696116531434, 35.528770239712671 ], [ 139.48697916524628, 35.528758239756669 ], [ 139.48707116492548, 35.528701239977224 ], [ 139.48718116452949, 35.528631240242774 ], [ 139.48733516299981, 35.528379240768558 ], [ 139.48751016214132, 35.528232241222426 ], [ 139.48766416135734, 35.528092241555086 ], [ 139.48775616075366, 35.527987241775882 ], [ 139.48779816011668, 35.527882241934364 ], [ 139.48779516005135, 35.527872241940671 ], [ 139.48774215905968, 35.527721242026033 ], [ 139.48763515834867, 35.527620241992487 ], [ 139.48760815817232, 35.527595241983441 ], [ 139.48746115751075, 35.527504241867554 ], [ 139.48730715705761, 35.527441241656781 ], [ 139.48718815657352, 35.527371241515226 ], [ 139.48706215608792, 35.527301241361222 ], [ 139.48695715547797, 35.52721024126555 ], [ 139.48691515437974, 35.527038241362888 ], [ 139.48688015370664, 35.526933241405665 ], [ 139.48684515338664, 35.526884241392445 ], [ 139.48681715306907, 35.526835241391666 ], [ 139.48674715260617, 35.526765241337223 ], [ 139.48665615204914, 35.526681241259446 ], [ 139.48658615171937, 35.526632241183997 ], [ 139.48653615135214, 35.526576241151112 ], [ 139.48652915086632, 35.526499241215667 ], [ 139.48653615016488, 35.52638724134011 ], [ 139.48663414777337, 35.526002241899334 ], [ 139.48668414730915, 35.525926242064223 ], [ 139.48671914673983, 35.525834242218451 ], [ 139.48675414657296, 35.525806242308668 ], [ 139.48687314629584, 35.52575724256922 ], [ 139.48704814590013, 35.525687242950333 ], [ 139.48711614566523, 35.525647243111223 ], [ 139.48716714548888, 35.525617243231885 ], [ 139.48729014436964, 35.525435243632558 ], [ 139.48735414377808, 35.525339243842339 ], [ 139.48740914327871, 35.52525824402111 ], [ 139.48746114280348, 35.525181244190556 ], [ 139.48749314234863, 35.52510824432045 ], [ 139.48751114210967, 35.525069244387431 ], [ 139.48757414119467, 35.524922244696292 ], [ 139.487594140228, 35.524775245016556 ], [ 139.48757613955598, 35.52467624519047 ], [ 139.48751813737732, 35.524355245755501 ], [ 139.48749113652423, 35.524229245966886 ], [ 139.48748013614178, 35.524172246061333 ], [ 139.48746813577245, 35.524117246149999 ], [ 139.48736313456911, 35.523940246317338 ], [ 139.48720813355465, 35.523793246335778 ], [ 139.48707813290579, 35.523700246290666 ], [ 139.48706113282199, 35.523688246284443 ], [ 139.48676013144845, 35.52349224614133 ], [ 139.48661313062246, 35.523373246117998 ], [ 139.48640312889577, 35.523121246248671 ], [ 139.48630512808066, 35.523002246312444 ], [ 139.48619312665576, 35.522792246533335 ], [ 139.4859111247531, 35.522516246584004 ], [ 139.48575012359066, 35.522347246635782 ], [ 139.4856941226449, 35.522207246816222 ], [ 139.48565912123712, 35.521997247173999 ], [ 139.48565912063711, 35.521907247354001 ], [ 139.48565911998378, 35.521809247549996 ], [ 139.48567311937356, 35.521717247758893 ], [ 139.48570811892134, 35.521648247959114 ], [ 139.48573411846047, 35.521578248145332 ], [ 139.48578511767843, 35.521459248474002 ], [ 139.48584111661756, 35.521298248895555 ], [ 139.485939115766, 35.521167249331775 ], [ 139.48615911401487, 35.520897250262884 ], [ 139.48627411310045, 35.520756250749329 ], [ 139.48641511159178, 35.520525251461997 ], [ 139.4864711101109, 35.52030125200956 ], [ 139.48645410929379, 35.520179252223329 ], [ 139.48645010907956, 35.520147252280225 ], [ 139.4863871076189, 35.519930252602222 ], [ 139.48633810700133, 35.519839252697111 ], [ 139.48623310660466, 35.519783252622439 ], [ 139.48598010626844, 35.519741252256672 ], [ 139.48572110616422, 35.51973425181022 ], [ 139.48544810619688, 35.519748251296889 ], [ 139.48514410630932, 35.519775250702445 ], [ 139.48513310631355, 35.519776250680891 ], [ 139.48487310685579, 35.519866250038667 ] ] ] } }
]
}

**Comment by trafficonese** [comment]
@osper66 Which version of Leaflet.glify did you use?

I am running the current Dev-version and the Polygon looks good to me, also while zooming etc..

![image](https://github.com/user-attachments/assets/5007c71d-79a0-4a54-8f01-8188d1fb901d)

**Comment by charlieforward9** [comment]
@trafficonese this one might just have to be called as resolved. I don't imagine anyone would remember a 7 year old problem too well 😂
