### ISSUE TITLE
Pinch Zoom to improve

### ISSUE THREAD

**Issue by YannNeobards** [robertleeplummerjr/Leaflet.glify#132]
Hello,

can you improve Pinch zoom events on mobile ?
when you use 2 fingers to zoom on mobile (chrome) the scaling is not done until release
would be great if improved

thanks

**Comment by YannNeobards** [comment]
I have fix it quikely (not sure good way) by adding event listener on `onAdd(`
```
onAdd(t) {
...
this.isAnimated() && t.on("zoom", this._reset, this),
this.isAnimated() && t.on("move", this._reset, this),

```
and 
```
onRemove(t)
...
this.isAnimated() && t.off("zoom", this._reset, this),
this.isAnimated() && t.off("move", this._reset, this),
```

add `'move'` event works fine for me to make it works properly with a `requestAnimationFrame(` changing color and use `.render()`

**Comment by charlieforward9** [comment]
Uploading zoom-issue.mov…

This is the problem I am facing, I will look where to add in your suggestion to see if it resolves the problem.

**Comment by charlieforward9** [comment]
https://github.com/user-attachments/assets/605b565a-4fcf-4d91-b663-9419fa238de9

This is the problem I am facing, I will look where to add in your suggestion to see if it resolves the problem.

**Comment by charlieforward9** [comment]
https://github.com/robertleeplummerjr/Leaflet.glify/commit/0bd921772b2100988b0b671f705c2a7ed1cab8d2 includes your [snippets](https://github.com/robertleeplummerjr/Leaflet.glify/issues/132#issuecomment-1150600128). 

Please add your email to your profile to be mentioned as a contributor in the commit. 

Thank you for the help.

**Comment by charlieforward9** [comment]
leaving open till I hear back or it is merged.
