### ISSUE TITLE
How to add a border on polygon when i use the  L.glify.shapes ?

### ISSUE THREAD

**Issue by JishuaiWang** [robertleeplummerjr/Leaflet.glify#14]
HI, I want to add a border on polygon  when i use the  L.glify.shapes  ;  The  fragmentShaderSource  what i use  is  L.glify.shader.fragment.polygon; Can you tell me  what should I do? or  How should I modify polygon.glsl file?   Your code is important to me. Thank you very much !

**Comment by JiShuaiWang** [comment]
@robertleeplummerjr

**Comment by robertleeplummerjr** [comment]
Currently the polygons are drawn from https://github.com/robertleeplummerjr/Leaflet.glify/blob/master/src/shader/fragment/polygon.glsl

We'd need to implement a polygon that is simply a bit smaller than the one being drawn, and then draw this over it.  Actually sounds really easy now that I think about it: https://stackoverflow.com/a/27764539/1324039

**Comment by JiShuaiWang** [comment]
Thank you for your response.
I have solved it 。The solution is inspired by  the method resetVertices();
I add  a  verts  to  record the borders  x / y , and  then draw twice . One is draw the polygons   and another one is draw the border.

**Comment by robertleeplummerjr** [comment]
Fantastic!  Would it be possible for you to put together a jsfiddle with your code so others can benefit (I'd love to see it as well).

**Comment by JiShuaiWang** [comment]
https://jsfiddle.net/33k83ek9/2/

**Comment by trafficonese** [comment]
The fiddle is not working anymore, as the data source has changed to:
`https://raw.githubusercontent.com/robertleeplummerjr/Leaflet.glify/master/data/CZDistricts.json`

**Comment by robertleeplummerjr** [comment]
Added in https://github.com/robertleeplummerjr/Leaflet.glify/pull/84
