### ISSUE TITLE
weird colors with "light" background tiles

### ISSUE THREAD

**Issue by tim-salabim** [robertleeplummerjr/Leaflet.glify#16]
When using tile providers with "light" colors (e.g. standard OpenStreetmap) the polygon fill colors get all messed up unless opacity is set to 1.

You can (maybe) reproduce this issue when replacing [this line](https://github.com/robertleeplummerjr/Leaflet.glify/blob/master/index.html#L40) with `L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);`

In Firefox on linux (Ubuntu 18.04) with default opacity I see:

![glify_light](https://user-images.githubusercontent.com/2826432/47962944-71f31280-e024-11e8-8864-6f21c04fa271.png)

whereas with opacity set to 1 I see:

![glify_light_o1](https://user-images.githubusercontent.com/2826432/47962945-76b7c680-e024-11e8-8e1f-ebe37c5d0d22.png)

Any ideas what might cause this strange behaviour? I am assuming this has something to do with shaders, but I have no experience with glsl.

For completeness, this was reported at https://github.com/tim-salabim/leaflet.glify/issues/4 where some more information can be found and which points to a browser issue as for some combinations of OS and browser this seems to be not a problem.

**Comment by nheir** [comment]
It look like its related to the `premultipliedAlpha` parameters of WebGL context canvas
