### ISSUE TITLE
how to update a point or remove a specific point on map 

### ISSUE THREAD

**Issue by khiemntu** [robertleeplummerjr/Leaflet.glify#19]
Anyone know solution for this problem ? thank you

**Comment by robertleeplummerjr** [comment]
A great use case that is not yet in existence.   Could you make a proposal and perhaps we can add it?

**Comment by robertleeplummerjr** [comment]
I suppose something  like: `.update(index, array)`?

**Comment by khiemntu** [comment]
Assume we have 1000 points on map with each point will have two params [lat, lng]. I need update the point with index 5 or the point with position [ 50, 14 ] to new position [ 10, 11] , and we also can update array of point to new position. Example:
`
point = pointArray[5]
point.update([10,11]) // lat, lng
// point.remove()
`

**Comment by robertleeplummerjr** [comment]
Based off that feedback (ty!), I'd like to go ahead and propose: 

1. `points.update(index, newArray)`
2. `points.remove(index)`

This allows is to use the existing API, but extend it in a way to maintain performance.

**Comment by pumano** [comment]
@robertleeplummerjr any news about that feature? 

I want to jump on board, but without realtime update, this solution not suitable to my needs.

**Comment by novaknole** [comment]
Still nothing?
