### ISSUE TITLE
Ability to change line thickness 

### ISSUE THREAD

**Issue by matthieugouel** [robertleeplummerjr/Leaflet.glify#36]
Hi ! 

First of all, thanks for your amazing plugin ! 
I wanted to now if there is a way to change a line thickness, in fact I would like to be able to reduce it. 

I try to tweak some variables with no luck. 

Best,
Matthieu.

**Comment by robertleeplummerjr** [comment]
I believe we have it now in the https://github.com/robertleeplummerjr/Leaflet.glify/tree/36-line-thickness branch.  Would you mind testing?  It is the "thickness" property.  If you have a better name for that property, by all means, suggest it.

**Comment by tim-salabim** [comment]
Re naming, leaflet refers to line thickness as "weight", so maybe that's what it should be called here too.

**Comment by robertleeplummerjr** [comment]
Changed.
