### ISSUE TITLE
needs to support lines

### ISSUE THREAD

**Issue by robertleeplummerjr** [robertleeplummerjr/Leaflet.glify#4]

**Comment by gisma** [comment]
I would highly appreciate the integration of lines... !
Do you have a rough imagination about a roadmap?

**Comment by gisma** [comment]
Just want to ask if there are any near future plans to implements the line feature?

**Comment by robertleeplummerjr** [comment]
There are plans to add these, but currently there isn't an active branch for it.

**Comment by cordovapolymer** [comment]
any plans to continue dev?

**Comment by robertleeplummerjr** [comment]
Yes.  Likely it'll be in the second or third quarter of 2017

**Comment by gillesgerlo** [comment]
Is this feature still planned? Would love it personally!

**Comment by robertleeplummerjr** [comment]
Still planned and will only take a few hours to implement, just looking for time.  Perhaps in the coming holiday when I need a break from other open source.

**Comment by gillesgerlo** [comment]
Thanks Robert, will keep an eye out for it!

**Comment by wimpel** [comment]
I am also looking forward for lines-implementation. Especially now that @tim-salabim has begun implementing your code into a package for R!

**Comment by robertleeplummerjr** [comment]
Added!  Ty @sashuk!

**Comment by tim-salabim** [comment]
Thanks to both of you! Will implement on my side asap

**Comment by gisma** [comment]
Great Thanks a lot!
