### ISSUE TITLE
Canvas empty on Reactjs

### ISSUE THREAD

**Issue by hungpp250795** [robertleeplummerjr/Leaflet.glify#40]
I had install Leaflet.glify on my Reactjs App(https://www.npmjs.com/package/leaflet.glify) and add to map by using this.ref.map.leafletElement button the canvas output are empty. Does not contain anything.
I add it by below code
let river = L.glify.lines({
        map: this.map.leafletElement,//this.map is my map ref
        data: this.context.riverJson,// your river.json data
        color: "#ff7800", 
        opacity: 1,
        className:"river-polyline"
      });
Is there any mistake from my understanding.

**Comment by charlieforward9** [comment]
Not enough information and outdated.
