### ISSUE TITLE
How is this supposed to be run in a browser?

### ISSUE THREAD

**Issue by esdot** [robertleeplummerjr/Leaflet.glify#45]
The src/index.js contains multiple readFileSync calls to get shaders, yet these file operations are not permitted in a browser. Is the intent that this index.js is part of a build process that produces the glify.js distribution file in the root of the repository? Currently I cannot successfully import the glify plugin using npm and webpack for this reason, I created a fork that adds what appears to be the glify.js distribution file in the root of the repository to the files in the package.json so I can import the built plugin using webpack. I apologize if I'm missing something obvious, this plugin is amazing and is a huge help in scaling my map to large datasets. I hope that I'm just not understanding something to your approach or perhaps a small change will allow me to use it as intended. Thanks!

PS the one line change in my fork can be viewed at the following link: [https://github.com/esdot/Leaflet.glify/commit/573e25ddb450571856969a8f49dc8ef41fd9255c](https://github.com/esdot/Leaflet.glify/commit/573e25ddb450571856969a8f49dc8ef41fd9255c)

**Comment by robertleeplummerjr** [comment]
Wanna open a PR?

**Comment by esdot** [comment]
I just opened a pull request. I totally understand - I'm just happy to have a plugin that achieves this functionality. Thanks!

**Comment by robertleeplummerjr** [comment]
Added

**Comment by robertleeplummerjr** [comment]
I'll get to releasing it this weekend.
