### ISSUE TITLE
Size is not working if size is a function in case of points

### ISSUE THREAD

**Issue by adiityasharrma** [robertleeplummerjr/Leaflet.glify#48]
@robertleeplummerjr 
Please look in to this.

I am using the below code :

L.glify.points({
							map: this.map,
							size: function(index,latLng){
								return 30;
							},
							click: function (e, point, xy) {
								//set up a standalone popup (use a popup as a layer)
								L.popup()
								.setLatLng(point)
								.setContent("My Tool tip")
								.openOn(this.map);
							},
							data: geoJSONObj,
							color: function(index,latLng){
								return {r:0, g:0,b:1};
							},
							opacity:0.8,
							fragmentShaderSource: function() { return tempGlifyMarker; }
						});

**Comment by robertleeplummerjr** [comment]
Ty for the housekeeping.

**Comment by tim-salabim** [comment]
Hi Robert, as I am not allowed to send via twitter or gmail, I am attaching an html here that does not show any points. Error is shown in the below pic

![Screenshot from 2020-03-06 14-24-57](https://user-images.githubusercontent.com/2826432/76098630-18a94380-5fca-11ea-9755-4613ea9c059f.png)

[test.zip](https://github.com/robertleeplummerjr/Leaflet.glify/files/4299144/test.zip)
