### ISSUE TITLE
Cool vector logo needed

### ISSUE THREAD

**Issue by robertleeplummerjr** [robertleeplummerjr/Leaflet.glify#50]
Community help wanted!

**Comment by jimbok8** [comment]
I don't know about cool! But this appealed to me, so here is my (probably not cool) offering,.
If you don't like it, or just think it is rubbish, then just ignore me!

It is a .SVG file in a .ZIP file. 
[GLiffy.zip](https://github.com/robertleeplummerjr/Leaflet.glify/files/4550549/GLiffy.zip)
Alterations and edits would be possible!.

**Comment by robertleeplummerjr** [comment]
I like it, but I think it needs simplification.  Too, we don't yet have a map pin, which is used in the background, so it could be a bit misleading.

**Comment by jimbok8** [comment]
OK, so the thinking was to bring in some element of Leaflet, hence the green 'leaves', this was the only shape I had at hand that looked remotely like a leaf.
I have added a second zip file with three more offerings, one with a green leaf background, and two more with simple rectangle backgrounds.
Again, do what you will with them.
Jim

[GLiffy2.zip](https://github.com/robertleeplummerjr/Leaflet.glify/files/4557022/GLiffy2.zip)

**Comment by RyanMattMcDonald** [comment]
Following @jimbok8 's ideas, sticking to a red+green color palette, if incorporating color at all, will provide congruity with Leaflet's green & WebGL' red. Here are a couple ideas.
![concept](https://user-images.githubusercontent.com/46179763/81460668-1008f100-9164-11ea-85e1-6c5e42dfad5d.png)

**Comment by SDR0512** [comment]
![05c12e84-c6f3-484b-83c4-30b91bf7c58e_200x200](https://user-images.githubusercontent.com/58349712/86570571-c2570c00-bf8d-11ea-99e6-0efd9507f67a.png)

**Comment by robertleeplummerjr** [comment]
I like what has been submitted so far, but can we go simpler?

What about the default logo for leaflet, but just the branches and leaves, but rainbow 
+psychedelic vectorised or rasterized?

Something unique.

**Comment by robertleeplummerjr** [comment]
For reference, here is the image: [](https://leafletjs.com/docs/images/logo.png)

**Comment by trafficonese** [comment]
Maybe something like this?

![leafletglify_logo](https://user-images.githubusercontent.com/35805180/95190758-157c6d00-07d0-11eb-868b-6153ad24f75f.png)

**Comment by trafficonese** [comment]
Would you like me to send you the SVG, include it in a PR, or let's wait and see what others think about it?

**Comment by robertleeplummerjr** [comment]
Send it!
