### ISSUE TITLE
Problems importing leaflet.glify with react

### ISSUE THREAD

**Issue by leodavinci1** [robertleeplummerjr/Leaflet.glify#57]
Hello guys I'm having this error when I import 'leaflet.glify' package:

> TypeError: fs.readFileSync is not a function
(anonymous function)
C:/Users/leo_c/Documents/projects/leo-gis-web/node_modules/leaflet.glify/src/js/index.js:212
  209 | },
  210 | mapMatrix: mapMatrix,
  211 | shader: {
> 212 |   vertex: fs.readFileSync(__dirname + '/../shader/vertex/default.glsl'),
      | ^  213 |   fragment: {
  214 |     dot: fs.readFileSync(__dirname + '/../shader/fragment/dot.glsl'),
  215 |     point: fs.readFileSync(__dirname + '/../shader/fragment/point.glsl'),
View compiled
./node_modules/leaflet.glify/src/js/index.js
http://localhost:3000/static/js/1.chunk.js:8881:30
__webpack_require__
C:/Users/leo_c/Documents/projects/leo-gis-web/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;
View compiled
fn

my code importing it:
` import 'leaflet.glify'; `

**Comment by faistos18** [comment]
Hi,

I have no experience with the React part of your problem so this may not work for you, but here's how I managed to get rid of the `fs` problem and import leaflet.glify with webpack :

 - `npm install leaflet.glify` (obviously)
 - Go to the file `node_modules/leaflet.glify/src/js/index.js`
 - delete the first line `var fs = require('fs');`
 - go at the end of the file, you will find all the usages of `fs`, like `vertex: fs.readFileSync(__dirname + '/../shader/vertex/default.glsl')`. It is just used to import the shaders
 - remove references to `fs` and copy-paste the content of the shader instead (between \`\` quotes) for shaders you use. For example, as I only used points, I copy-pasted `vertex/default.glsl` and `fragments/point.glsl`, and leaved the rest as \`\`

This is obviously a hack, but the `fs` library here is `brfs` which is a browserify dependency.
You can also check on [webpack-contrib ](https://github.com/webpack-contrib/transform-loader), webpack tools to allow browserify transforms, but for a few shaders, I think it's not really worth the pain.

In the long run, I hope that it will be possible to remove the dependency to `brfs` and go for something like `glslify-require` instead, like done [here](https://github.com/robertleeplummerjr/Leaflet.glify/pull/55/commits/01070788987c55e132a0b35471bccf84666686c4).

Hope this works for you !

**Comment by jhamberg** [comment]
Coincidentally, I also managed to solve this issue just today with the following steps:
1) Install transform-loader `npm install --save-dev transform-loader`
2) Install brfs `npm install --save-dev brfs`
3) Add the following to `webpack.config.js`:
```js
  module: {
    rules: [{
      test: /\/node_modules\/leaflet\.glify\/src\/js\/index\.js/,
      loader: "transform-loader?brfs"
    }]
  }
```
The regex captures the full path to glify's index.js because the brfs transform does not seem to support files with ES6 imports (which would be common in my project).

If you are using [create-react-app](https://github.com/facebook/create-react-app) you might need to run `npm run eject` or figure out another way to configure the transform-loader module.

**Comment by leodavinci1** [comment]
I have removed fs and it did solve my problem, thanks guys

**Comment by robertleeplummerjr** [comment]
What could we do to provide a fix for many regarding this issue?  PR's are welcome.

**Comment by leodavinci1** [comment]
I have encoded the shader into a base64 string,

` vertex: Buffer("dW5pZm9ybS ... yOwp9", "base64") `

Definitely a hack but fixed my problem developing with react.
