### ISSUE TITLE
Is there any way to remove all points or to clean the canvas?

### ISSUE THREAD

**Issue by leodavinci1** [robertleeplummerjr/Leaflet.glify#59]
I'm developing a data filter that would update the rendered points according to the user specific data filters, but how can I remove the points so I can add the new filtered ones?

**Comment by leodavinci1** [comment]
Found native leaflet alternative

**Comment by jwoodmansey** [comment]
For anyone looking for a solution to this, if you keep your state separate and run this in a function when your data changes, it seems to work well:

```
    const { glify } = L;
    const instance = glify.Points.instances[0];
    if (instance) {
      instance.setData(data);
      instance.setup().render();
    } else {
      glify.points({
        data,
        ...the rest of your settings
      });
    }
```
