### ISSUE TITLE
Critical dependency warning

### ISSUE THREAD

**Issue by Garlink** [robertleeplummerjr/Leaflet.glify#70]
Getting a Critical dependency warning related to glify-browser.js

```
./node_modules/leaflet.glify/dist/glify-browser.js
Critical dependency: the request of a dependency is an expression
```

I can't find much about this, but it seems to be related to using Parcel bundled packages on Webpack bundled apps.

In my case I am using glify with a [CRA](https://github.com/facebook/create-react-app) app. All seems to be working fine, but this warning is kind of annoying.

Is there any fix for this?

**Comment by trafficonese** [comment]
This can be closed, since we are not using Parcel anymore.
