### ISSUE TITLE
glify throws 'unhandled polygon' error while reading geojson

### ISSUE THREAD

**Issue by nzahasan** [robertleeplummerjr/Leaflet.glify#86]
This error is occurring with this polygon
https://drive.google.com/file/d/1iGyt2mPuBUxeohLCe5IFdE3ZkbFcLu6r/view?usp=sharing

**Comment by robertleeplummerjr** [comment]
Is this no longer an issue?

**Comment by robertleeplummerjr** [comment]
Let's keep this open till it is confirmed handled.

**Comment by trafficonese** [comment]
I can read the Polygon with the current Dev version, so the issue should be resolved.
![image](https://github.com/user-attachments/assets/6f79eee9-d557-4dbe-ae6b-388c886272f3)

**Comment by nzahasan** [comment]
awesome
