### ISSUE TITLE
Leaflet 1.7 + VueJS 

### ISSUE THREAD

**Issue by DerecksonS** [robertleeplummerjr/Leaflet.glify#87]
Hello, first, I would like to congratulate the Leaflet plugin. 

It has a spectacular performance and for this reason, I wanted to add this to my project, which also uses VueJS and Leaflet, however, I can't use the glify layer as shown in the example.

![image](https://user-images.githubusercontent.com/7096375/100207610-b1d50d00-2eff-11eb-9ab7-288d06a1511a.png)

**Comment by xlcrr** [comment]
Same error here. Any update? Just getting started on this

**Comment by robertleeplummerjr** [comment]
Can you try with the latest from master branch and let me know if it works?

**Comment by xlcrr** [comment]
The package works fine, but the critical error shows

**Comment by robertleeplummerjr** [comment]
How can I reproduce?

**Comment by xlcrr** [comment]
We are using Glify at [openlittermap](https://openlittermap.com/global) which has vue integration

You could try install our repo locally, `npm install` and then `npm run dev` which will compile `resources/js` and put it into `public/js/app.js` via webpack.mix.js

**Comment by rodinf** [comment]
Any updates?

**Comment by robertleeplummerjr** [comment]
Reproduced using the method described by @xlcrr.  Looking in to solution.  Ty for the reminder.

**Comment by robertleeplummerjr** [comment]
ping

**Comment by robertleeplummerjr** [comment]
Released: https://www.npmjs.com/package/leaflet.glify/v/3.2.0
