### ISSUE TITLE
"Hover off" functionality

### ISSUE THREAD

**Issue by lthurner** [robertleeplummerjr/Leaflet.glify#92]
Very grateful for the addition of hover events for lines and points in #53, works very nicely @trafficonese! 

One question on the usage: is there a way to detect when the user is not hovering over an element anymore? I want to display an info box when hovering over a point, but can't get it to disappear after the cursor leaves the point. Basicly I am looking for an equivalent of leaflets "mouseout" event.

Am I missing something in how to use the feature, or would this need to be implemented?

**Comment by thor85** [comment]
I don't think there is currently. I am also displaying hover data in an info box, and I added a quick fix in my own fork to get mouseOut working. I can try and clean it up and make a new pull request. I am not sure it's the best way to implement it though. We'll see if it get's merged :smile:
